package domain.usecase.temperatureFason

import domain.usecase.temperatureFason.inputParam.TemperatureFasonInputParam
import domain.usecase.temperatureFason.outputParam.TemperatureFasonOutputParam

interface TemperatureFason : (TemperatureFasonInputParam) -> TemperatureFasonOutputParam